#ifdef COLLISION_PURE_VIRTUAL
#define COLLISION_DECLARATION(OTHER_CLASS) virtual void collideWith(OTHER_CLASS &other) = 0;
#undef COLLISION_PURE_VIRTUAL
#else
#define COLLISION_DECLARATION(OTHER_CLASS) virtual void collideWith(OTHER_CLASS &other);
#endif

COLLISION_DECLARATION(Aegrum)
COLLISION_DECLARATION(Boss)
COLLISION_DECLARATION(Character)
COLLISION_DECLARATION(Corona)
COLLISION_DECLARATION(Enemy)
COLLISION_DECLARATION(Justitia)
COLLISION_DECLARATION(Magus)
COLLISION_DECLARATION(MovableObject)
COLLISION_DECLARATION(Obex)
COLLISION_DECLARATION(PhysicalObject)
COLLISION_DECLARATION(Player)
COLLISION_DECLARATION(Scenery)
COLLISION_DECLARATION(Spike)
COLLISION_DECLARATION(Turris)
COLLISION_DECLARATION(Vagus)
COLLISION_DECLARATION(Vis)

#undef COLLISION_DECLARATION