#ifndef FANCY_ASSERT_H
#define FANCY_ASSERT_H

// Fancy assertions
#include "lib/pempek_assert.h"
#define ASSERT          PEMPEK_ASSERT
#define ASSERT_WARNING  PEMPEK_ASSERT_WARNING
#define ASSERT_DEBUG    PEMPEK_ASSERT_DEBUG
#define ASSERT_ERROR    PEMPEK_ASSERT_ERROR
#define ASSERT_FATAL    PEMPEK_ASSERT_FATAL
#define ASSERT_CUSTOM   PEMPEK_ASSERT_CUSTOM
#define ASSERT_USED     PEMPEK_ASSERT_USED

#endif